# Generated by Django 3.0.3 on 2020-07-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='image',
            new_name='img',
        ),
    ]
